import { Inter } from 'next/font/google';

import './globals.scss'

import Intro from '../Components/Intro/Intro'
import Header from '../Components/Header/Header'
import BackgroundVideo from '../Components/BackgroundVideo/BackgroundVideo'

export const metadata = {
  title: 'B O G G E D',
  description: 'Generated by create next app',
}

const font = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        {children}
        <BackgroundVideo />
        <Intro />
      </body>
    </html>
  )
}